/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PagamentiService } from "../pagamenti.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PagamentiCreateInput } from "./PagamentiCreateInput";
import { Pagamenti } from "./Pagamenti";
import { PagamentiFindManyArgs } from "./PagamentiFindManyArgs";
import { PagamentiWhereUniqueInput } from "./PagamentiWhereUniqueInput";
import { PagamentiUpdateInput } from "./PagamentiUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PagamentiControllerBase {
  constructor(
    protected readonly service: PagamentiService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Pagamenti })
  @nestAccessControl.UseRoles({
    resource: "Pagamenti",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPagamenti(
    @common.Body() data: PagamentiCreateInput
  ): Promise<Pagamenti> {
    return await this.service.createPagamenti({
      data: data,
      select: {
        aggiungiEntrata: true,
        aggiungiSpesa: true,
        avere: true,
        createdAt: true,
        dare: true,
        id: true,
        nonPagati: true,
        pagati: true,
        riepilogo: true,
        rimanenza: true,
        storicoPagamenti: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Pagamenti] })
  @ApiNestedQuery(PagamentiFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Pagamenti",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pagamentis(@common.Req() request: Request): Promise<Pagamenti[]> {
    const args = plainToClass(PagamentiFindManyArgs, request.query);
    return this.service.pagamentis({
      ...args,
      select: {
        aggiungiEntrata: true,
        aggiungiSpesa: true,
        avere: true,
        createdAt: true,
        dare: true,
        id: true,
        nonPagati: true,
        pagati: true,
        riepilogo: true,
        rimanenza: true,
        storicoPagamenti: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Pagamenti })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Pagamenti",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pagamenti(
    @common.Param() params: PagamentiWhereUniqueInput
  ): Promise<Pagamenti | null> {
    const result = await this.service.pagamenti({
      where: params,
      select: {
        aggiungiEntrata: true,
        aggiungiSpesa: true,
        avere: true,
        createdAt: true,
        dare: true,
        id: true,
        nonPagati: true,
        pagati: true,
        riepilogo: true,
        rimanenza: true,
        storicoPagamenti: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Pagamenti })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Pagamenti",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePagamenti(
    @common.Param() params: PagamentiWhereUniqueInput,
    @common.Body() data: PagamentiUpdateInput
  ): Promise<Pagamenti | null> {
    try {
      return await this.service.updatePagamenti({
        where: params,
        data: data,
        select: {
          aggiungiEntrata: true,
          aggiungiSpesa: true,
          avere: true,
          createdAt: true,
          dare: true,
          id: true,
          nonPagati: true,
          pagati: true,
          riepilogo: true,
          rimanenza: true,
          storicoPagamenti: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Pagamenti })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Pagamenti",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePagamenti(
    @common.Param() params: PagamentiWhereUniqueInput
  ): Promise<Pagamenti | null> {
    try {
      return await this.service.deletePagamenti({
        where: params,
        select: {
          aggiungiEntrata: true,
          aggiungiSpesa: true,
          avere: true,
          createdAt: true,
          dare: true,
          id: true,
          nonPagati: true,
          pagati: true,
          riepilogo: true,
          rimanenza: true,
          storicoPagamenti: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
