/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Pagamenti as PrismaPagamenti } from "@prisma/client";

export class PagamentiServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.PagamentiCountArgs, "select">
  ): Promise<number> {
    return this.prisma.pagamenti.count(args);
  }

  async pagamentis<T extends Prisma.PagamentiFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.PagamentiFindManyArgs>
  ): Promise<PrismaPagamenti[]> {
    return this.prisma.pagamenti.findMany<Prisma.PagamentiFindManyArgs>(args);
  }
  async pagamenti<T extends Prisma.PagamentiFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.PagamentiFindUniqueArgs>
  ): Promise<PrismaPagamenti | null> {
    return this.prisma.pagamenti.findUnique(args);
  }
  async createPagamenti<T extends Prisma.PagamentiCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.PagamentiCreateArgs>
  ): Promise<PrismaPagamenti> {
    return this.prisma.pagamenti.create<T>(args);
  }
  async updatePagamenti<T extends Prisma.PagamentiUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.PagamentiUpdateArgs>
  ): Promise<PrismaPagamenti> {
    return this.prisma.pagamenti.update<T>(args);
  }
  async deletePagamenti<T extends Prisma.PagamentiDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.PagamentiDeleteArgs>
  ): Promise<PrismaPagamenti> {
    return this.prisma.pagamenti.delete(args);
  }
}
