import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { StringFilter } from "../../util/StringFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";

export type ImmobiliWhereInput = {
  canone?: FloatNullableFilter;
  cap?: StringNullableFilter;
  caparraIniziale?: FloatNullableFilter;
  categoriaCatasto?: StringNullableFilter;
  citt?: StringNullableFilter;
  classe?: StringNullableFilter;
  contratto?: JsonFilter;
  descrizione?: StringNullableFilter;
  documenti?: JsonFilter;
  foglioCatastale?: StringNullableFilter;
  foto?: JsonFilter;
  id?: StringFilter;
  imu?: FloatNullableFilter;
  indirizzo?: StringNullableFilter;
  mq2?: IntNullableFilter;
  note?: StringNullableFilter;
  numero?: StringNullableFilter;
  numeroLocali?: IntNullableFilter;
  numeroLocaliAggiuntivi?: IntNullableFilter;
  paese?: StringNullableFilter;
  particella?: StringNullableFilter;
  partita?: StringNullableFilter;
  piani?: IntNullableFilter;
  regione?: StringNullableFilter;
  renditaCatastale?: FloatNullableFilter;
  riferimentiCatastali?: StringNullableFilter;
  sezioneUrbana?: StringNullableFilter;
  spese?: FloatNullableFilter;
  subalterno?: StringNullableFilter;
  tipoLocazione?: StringNullableFilter;
  tipologiaPropriet?: StringNullableFilter;
  zonaCensuaria?: StringNullableFilter;
};
