/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UtentiService } from "../utenti.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UtentiCreateInput } from "./UtentiCreateInput";
import { Utenti } from "./Utenti";
import { UtentiFindManyArgs } from "./UtentiFindManyArgs";
import { UtentiWhereUniqueInput } from "./UtentiWhereUniqueInput";
import { UtentiUpdateInput } from "./UtentiUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UtentiControllerBase {
  constructor(
    protected readonly service: UtentiService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Utenti })
  @nestAccessControl.UseRoles({
    resource: "Utenti",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createUtenti(@common.Body() data: UtentiCreateInput): Promise<Utenti> {
    return await this.service.createUtenti({
      data: data,
      select: {
        codiceFiscale: true,
        cognome: true,
        createdAt: true,
        dataNascita: true,
        documenti: true,
        documentoIdentit: true,
        email: true,
        id: true,
        luogoNascita: true,
        nome: true,
        note: true,
        telefono: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Utenti] })
  @ApiNestedQuery(UtentiFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Utenti",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async utentis(@common.Req() request: Request): Promise<Utenti[]> {
    const args = plainToClass(UtentiFindManyArgs, request.query);
    return this.service.utentis({
      ...args,
      select: {
        codiceFiscale: true,
        cognome: true,
        createdAt: true,
        dataNascita: true,
        documenti: true,
        documentoIdentit: true,
        email: true,
        id: true,
        luogoNascita: true,
        nome: true,
        note: true,
        telefono: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Utenti })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Utenti",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async utenti(
    @common.Param() params: UtentiWhereUniqueInput
  ): Promise<Utenti | null> {
    const result = await this.service.utenti({
      where: params,
      select: {
        codiceFiscale: true,
        cognome: true,
        createdAt: true,
        dataNascita: true,
        documenti: true,
        documentoIdentit: true,
        email: true,
        id: true,
        luogoNascita: true,
        nome: true,
        note: true,
        telefono: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Utenti })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Utenti",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateUtenti(
    @common.Param() params: UtentiWhereUniqueInput,
    @common.Body() data: UtentiUpdateInput
  ): Promise<Utenti | null> {
    try {
      return await this.service.updateUtenti({
        where: params,
        data: data,
        select: {
          codiceFiscale: true,
          cognome: true,
          createdAt: true,
          dataNascita: true,
          documenti: true,
          documentoIdentit: true,
          email: true,
          id: true,
          luogoNascita: true,
          nome: true,
          note: true,
          telefono: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Utenti })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Utenti",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUtenti(
    @common.Param() params: UtentiWhereUniqueInput
  ): Promise<Utenti | null> {
    try {
      return await this.service.deleteUtenti({
        where: params,
        select: {
          codiceFiscale: true,
          cognome: true,
          createdAt: true,
          dataNascita: true,
          documenti: true,
          documentoIdentit: true,
          email: true,
          id: true,
          luogoNascita: true,
          nome: true,
          note: true,
          telefono: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
